/-
# `Cl_coh(𝕋)` — the free *coherent* traced SMC, and its universal functor

[`Free.lean`](Free.lean) builds `Cl 𝕋`, the free traced SMC for the **bare** typeclass
(matching the doctrine's thesis that the trace needs no coherence). This file builds the
**coherent** refinement: the free `CoherentTracedSMC` on the same signature, by quotienting the
syntax by `CohRel` — the bare congruence `Rel` (embedded via `ofRel`) *plus* the eight monoidal
coherence equations. It reuses `Free`'s `Term`, `interpTerm`, and `interp_respects` wholesale.

* `CohRel` — `Rel` ⊕ the coherence laws, closed under equivalence and congruence;
* `clCoherentTracedSMC : CoherentTracedSMC` — `Quot CohRel` is a coherent traced SMC;
* `functorC` — the universal functor `Cl_coh(𝕋) ⟶ 𝒟` into any **coherent** model, the bare
  `interp_respects` discharging the `ofRel` steps and `𝒟`'s coherence fields the rest.

So both free objects exist: the bare `Cl 𝕋` (doctrine-faithful) and the coherent `Cl_coh 𝕋`.
-/
import RelExist.Free
import RelExist.Coherence

namespace RelExist.Free

open RelExist.Traced

universe u
variable {C : Type u} {G : Obj C → Obj C → Type u}

/-- The congruence generated by the bare laws (`Rel`, embedded via `ofRel`) **and** the eight
monoidal coherence equations. Quotienting by it gives the free *coherent* traced SMC. -/
inductive CohRel : {X Y : Obj C} → Term G X Y → Term G X Y → Prop
  -- the bare congruence, plus equivalence/congruence closure for the new equations
  | ofRel {X Y} {a b : Term G X Y} : Rel a b → CohRel a b
  | symm {X Y} {a b : Term G X Y} : CohRel a b → CohRel b a
  | trans {X Y} {a b c : Term G X Y} : CohRel a b → CohRel b c → CohRel a c
  | comp_cong {X Y Z} {f f' : Term G X Y} {g g' : Term G Y Z} :
      CohRel f f' → CohRel g g' → CohRel (.comp f g) (.comp f' g')
  | tensH_cong {X Y Z W} {f f' : Term G X Y} {g g' : Term G Z W} :
      CohRel f f' → CohRel g g' → CohRel (.tensH f g) (.tensH f' g')
  | tr_cong {X Y U} {f f' : Term G (.tens X U) (.tens Y U)} :
      CohRel f f' → CohRel (.tr f) (.tr f')
  -- the coherence laws
  | assoc_nat {X X' Y Y' Z Z'} (f : Term G X X') (g : Term G Y Y') (h : Term G Z Z') :
      CohRel (.comp (.tensH (.tensH f g) h) (.aHom X' Y' Z'))
             (.comp (.aHom X Y Z) (.tensH f (.tensH g h)))
  | lu_nat {X Y} (f : Term G X Y) :
      CohRel (.comp (.tensH (.id .unit) f) (.luHom Y)) (.comp (.luHom X) f)
  | ru_nat {X Y} (f : Term G X Y) :
      CohRel (.comp (.tensH f (.id .unit)) (.ruHom Y)) (.comp (.ruHom X) f)
  | pentagon (W X Y Z) :
      CohRel (.comp (.aHom (.tens W X) Y Z) (.aHom W X (.tens Y Z)))
             (.comp (.tensH (.aHom W X Y) (.id Z))
               (.comp (.aHom W (.tens X Y) Z) (.tensH (.id W) (.aHom X Y Z))))
  | triangle (X Y) :
      CohRel (.comp (.aHom X .unit Y) (.tensH (.id X) (.luHom Y))) (.tensH (.ruHom X) (.id Y))
  | braid_nat {X X' Y Y'} (f : Term G X X') (g : Term G Y Y') :
      CohRel (.comp (.tensH f g) (.braid X' Y')) (.comp (.braid X Y) (.tensH g f))
  | braid_symm (X Y) : CohRel (.comp (.braid X Y) (.braid Y X)) (.id (.tens X Y))
  | hexagon (X Y Z) :
      CohRel (.comp (.aHom X Y Z) (.comp (.braid X (.tens Y Z)) (.aHom Y Z X)))
             (.comp (.tensH (.braid X Y) (.id Z))
               (.comp (.aHom Y X Z) (.tensH (.id Y) (.braid X Z))))

variable (G)

/-- Morphisms of the free coherent traced SMC: terms modulo `CohRel`. -/
abbrev HomC (X Y : Obj C) : Type u := Quot (@CohRel C G X Y)

/-- The identity. -/
def qidC (X : Obj C) : HomC G X X := Quot.mk _ (Term.id X)

/-- Composition, descended through the coherent quotient. -/
def qcompC {X Y Z} : HomC G X Y → HomC G Y Z → HomC G X Z :=
  Quot.lift
    (fun f => Quot.lift (fun g => Quot.mk (@CohRel C G X Z) (Term.comp f g))
        (fun _ _ hg => Quot.sound (CohRel.comp_cong (CohRel.ofRel (Rel.refl _)) hg)))
    (fun _ _ hf => funext fun qg =>
      Quot.inductionOn qg (fun _ => Quot.sound (CohRel.comp_cong hf (CohRel.ofRel (Rel.refl _)))))

/-- Tensor of morphisms, descended through the coherent quotient. -/
def qtensHC {X Y Z W} : HomC G X Y → HomC G Z W → HomC G (.tens X Z) (.tens Y W) :=
  Quot.lift
    (fun f => Quot.lift (fun g => Quot.mk (@CohRel C G _ _) (Term.tensH f g))
        (fun _ _ hg => Quot.sound (CohRel.tensH_cong (CohRel.ofRel (Rel.refl _)) hg)))
    (fun _ _ hf => funext fun qg =>
      Quot.inductionOn qg (fun _ => Quot.sound (CohRel.tensH_cong hf (CohRel.ofRel (Rel.refl _)))))

/-- Trace, descended through the coherent quotient. -/
def qtrC {X Y U} : HomC G (.tens X U) (.tens Y U) → HomC G X Y :=
  Quot.lift (fun f => Quot.mk (@CohRel C G X Y) (Term.tr f))
    (fun _ _ hf => Quot.sound (CohRel.tr_cong hf))

/-- **`Cl_coh 𝕋` is a coherent traced symmetric monoidal category.** The free one on the
signature: every bare axiom holds via an embedded `Rel` generator, and each of the eight
coherence laws via its `CohRel` generator. -/
def clCoherentTracedSMC : CoherentTracedSMC.{u, u} where
  Obj := Obj C
  Hom := HomC G
  id := qidC G
  comp := qcompC G
  id_comp := by intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.ofRel (Rel.id_comp f))
  comp_id := by intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.ofRel (Rel.comp_id f))
  assoc := by
    intro W X Y Z f g h
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    induction h using Quot.ind with | _ h =>
    exact Quot.sound (CohRel.ofRel (Rel.assoc f g h))
  tens := Obj.tens
  unit := Obj.unit
  tensH := qtensHC G
  braid := fun X Y => Quot.mk _ (Term.braid X Y)
  trace := qtrC G
  aHom := fun X Y Z => Quot.mk _ (Term.aHom X Y Z)
  aInv := fun X Y Z => Quot.mk _ (Term.aInv X Y Z)
  a_hom_inv := fun X Y Z => Quot.sound (CohRel.ofRel (Rel.a_hom_inv X Y Z))
  a_inv_hom := fun X Y Z => Quot.sound (CohRel.ofRel (Rel.a_inv_hom X Y Z))
  ruHom := fun X => Quot.mk _ (Term.ruHom X)
  ruInv := fun X => Quot.mk _ (Term.ruInv X)
  ru_hom_inv := fun X => Quot.sound (CohRel.ofRel (Rel.ru_hom_inv X))
  ru_inv_hom := fun X => Quot.sound (CohRel.ofRel (Rel.ru_inv_hom X))
  luHom := fun X => Quot.mk _ (Term.luHom X)
  luInv := fun X => Quot.mk _ (Term.luInv X)
  lu_hom_inv := fun X => Quot.sound (CohRel.ofRel (Rel.lu_hom_inv X))
  lu_inv_hom := fun X => Quot.sound (CohRel.ofRel (Rel.lu_inv_hom X))
  trace_nat_left := by
    intro X X' Y U g f
    induction g using Quot.ind with | _ g =>
    induction f using Quot.ind with | _ f =>
    exact Quot.sound (CohRel.ofRel (Rel.trace_nat_left g f))
  trace_nat_right := by
    intro X Y Y' U f g
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    exact Quot.sound (CohRel.ofRel (Rel.trace_nat_right f g))
  trace_slide := by
    intro X Y U V f h
    induction f using Quot.ind with | _ f =>
    induction h using Quot.ind with | _ h =>
    exact Quot.sound (CohRel.ofRel (Rel.trace_slide f h))
  trace_yank := fun U => Quot.sound (CohRel.ofRel (Rel.trace_yank U))
  trace_vanish_unit := by
    intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.ofRel (Rel.trace_vanish_unit f))
  trace_vanish_tens := by
    intro X Y U V f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.ofRel (Rel.trace_vanish_tens f))
  trace_superpose := by
    intro W X Y U f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.ofRel (Rel.trace_superpose f))
  -- the coherence layer
  assoc_nat := by
    intro X X' Y Y' Z Z' f g h
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    induction h using Quot.ind with | _ h =>
    exact Quot.sound (CohRel.assoc_nat f g h)
  lu_nat := by intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.lu_nat f)
  ru_nat := by intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (CohRel.ru_nat f)
  pentagon := fun W X Y Z => Quot.sound (CohRel.pentagon W X Y Z)
  triangle := fun X Y => Quot.sound (CohRel.triangle X Y)
  braid_nat := by
    intro X X' Y Y' f g
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    exact Quot.sound (CohRel.braid_nat f g)
  braid_symm := fun X Y => Quot.sound (CohRel.braid_symm X Y)
  hexagon := fun X Y Z => Quot.sound (CohRel.hexagon X Y Z)

/-! ### The universal functor into a coherent model -/

variable (𝒟 : CoherentTracedSMC.{u, u}) (ιC : C → 𝒟.Obj)
  (ιG : {X Y : Obj C} → G X Y → 𝒟.Hom (interpObj 𝒟.toTracedSMC ιC X) (interpObj 𝒟.toTracedSMC ιC Y))

/-- The interpretation respects `CohRel`: the embedded bare steps by `interp_respects`, the
equivalence/congruence steps by `Eq`'s laws, and the eight coherence steps by `𝒟`'s coherence
fields. So it descends to the coherent quotient. -/
theorem interpC_respects {X Y} {a b : Term G X Y} (h : CohRel a b) :
    interpTerm 𝒟.toTracedSMC ιC ιG a = interpTerm 𝒟.toTracedSMC ιC ιG b := by
  induction h with
  | ofRel hr => exact interp_respects G 𝒟.toTracedSMC ιC ιG hr
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | comp_cong _ _ ihf ihg => show 𝒟.comp _ _ = 𝒟.comp _ _; rw [ihf, ihg]
  | tensH_cong _ _ ihf ihg => show 𝒟.tensH _ _ = 𝒟.tensH _ _; rw [ihf, ihg]
  | tr_cong _ ih => show 𝒟.trace _ = 𝒟.trace _; rw [ih]
  | assoc_nat f g h => exact 𝒟.assoc_nat _ _ _
  | lu_nat f => exact 𝒟.lu_nat _
  | ru_nat f => exact 𝒟.ru_nat _
  | pentagon W X Y Z => exact 𝒟.pentagon _ _ _ _
  | triangle X Y => exact 𝒟.triangle _ _
  | braid_nat f g => exact 𝒟.braid_nat _ _
  | braid_symm X Y => exact 𝒟.braid_symm _ _
  | hexagon X Y Z => exact 𝒟.hexagon _ _ _

/-- **The universal functor out of the free coherent traced SMC.** A model of the signature in
a *coherent* `𝒟` extends to a traced functor `Cl_coh 𝕋 ⟶ 𝒟` — coherence on both sides. -/
def functorC : TracedFunctor (clCoherentTracedSMC G).toTracedSMC 𝒟.toTracedSMC where
  obj := interpObj 𝒟.toTracedSMC ιC
  map := fun {_ _} => Quot.lift (interpTerm 𝒟.toTracedSMC ιC ιG)
    (fun _ _ h => interpC_respects G 𝒟 ιC ιG h)
  obj_tens := fun _ _ => rfl
  obj_unit := rfl
  map_id := fun _ => rfl
  map_comp := by
    intro X Y Z f g
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    rfl

end RelExist.Free
