I cloned it and read the charter (all revisions), both summaries, and all ten Lean files line by line. Verdict first: the infrastructure is real and the honesty machinery (naming discipline, errata, typed holes) is genuinely good practice — but there's a recurring failure mode where the *formal statement* is far weaker than the *label and gloss* placed on it, and a few headline claims in the summaries are not what the Lean proves. A referee will find these. Here's the audit.

**What's genuinely solid.** The QPF/`Cofix` construction of the carrier (eliminating the stabilization axiom) is real work. The Klin–Salamanca port (`ws3_no_distributive_law`) is the most substantial mathematics in the repo. The exponential-replicator Lipschitz estimate with an explicit constant is honest analysis, and the surfaced design corrections (pentagon signature, `Nonempty M`, the `1/δ` fix) are exemplary. WS2's weak-pullback and bisimulation theory is competent.

**Overreach 1 — "inhabited at one concrete tuple" is false as stated.** `ws7_retro_validate` and `ws7_band_and_retro` are universally quantified schemas: no concrete `κ₀` is ever instantiated, and every one of them takes `hcard : κ ≤ #(νPk κ).X` as an *unproved hypothesis*. That hypothesis also sits under `ws6_no_maximal`, `ws6_no_global_observer`, and the static band — so "no maximal, Discharged" and "(vi), Discharged" are all conditional. The good news: `hcard` is provable in a few lines — if `#X < κ` then `PkObj κ X = Set X`, and Lambek gives `X ≃ Set X`, contradicting Cantor. Prove it, instantiate `κ₀ := ℵ₀` (regular, in Mathlib), and the witnessed-tuple claim becomes true. Right now it isn't.

**Overreach 2 — "canonicity" is a near-tautology.** `ws3_weak_law_canonical` proves uniqueness of the map satisfying `str (f t) = pkJoin (map str t)` — but since `str` is a bijection, that equation *defines* f; uniqueness is injectivity of `destEquiv`, full stop. What §6.1 pinned was canonicity *among weak distributive laws* (uniqueness over natural transformations satisfying the weak-law axioms — the Garner-style question). That is untouched, yet it's the peg on which criterion (iv) moved to Discharged.

**Overreach 3 — the incompleteness theorem doesn't involve attention or finiteness.** `ws5_carrier_incomplete` is bare Cantor: no surjection from any set onto its own powerset. The `< κ` bound, the coalgebra structure, and attention appear nowhere in the proof — the theorem is true of any set whatsoever. The advertised "(F, κ)-robustness" is just this structure-independence, reframed as strength. So the charter's central move — "finite attention is exactly the non-surjectivity that lets a self-referential system remain consistent" — is not supported: the result would hold for an infinite, unbounded, attention-free object too. The philosophical content lives entirely in the modeling choice that "self-description space" = predicates over the support, which no theorem defends (and `ws5_self_enumerates_relations` shows the result flips under the other natural choice).

**Overreach 4 — criterion (vi) is discharged by trivialities.** `ws6_substantive_standpoints` says distinct successor sets give distinct membership predicates — definitionally true. `ws6_poles_split` is worse: `FaithfulCarrierEmbedding` carries κ as a *phantom parameter* — the carrier appears in none of its fields. The theorem is "a faithful functor from a category with two distinct parallel arrows can't land entirely in terminal objects," a two-line fact about any category, glossed as "the charter's atom = everything trivialization, proved fatal." Nothing ties it to νP_κ.

**Overreach 5 — the atomlessness claim has a live counterexample in-house.** The technical summary calls criterion (i) "Discharged — atomlessness is automatic for a terminal coalgebra." But the carrier contains the empty-successor state (`bottomState`) — an object that decomposes into *no* relations, i.e., exactly what Commitment 1 forbids — and you *use* it to refute `GeneralBranching`. There is no formal atomlessness theorem anywhere; grep confirms it. Lambek's iso doesn't preclude empty unfoldings. Either define "atom" formally so that ∅ isn't one (and defend that), or carve out the hereditarily-nonempty subcoalgebra as the actual deliverable for (i). As built, the object is not groundless; it *contains* a groundless region.

**Overreach 6 — the convergence story.** Three issues. (a) The dynamics live on an abstract `Fintype` simplex never connected to `Attn`/the carrier — `SelfSupport` can be infinite, `FlooredSimplex` requires finite S, and no bridging theorem exists; "attention on the carrier converges" is comment-level only. (b) Both summaries assert convergence "really can fail below the threshold" / "contraction genuinely fails below μ⋆" — nothing proves this; the bands come from Lipschitz *upper bounds*, which aren't sharp, so `μ⋆` is a threshold of the estimate, not of the dynamics. No divergence example exists. (c) The linear band `2(1−μ) < μ·u_min` forces μ ≈ 1: convergence is proved only where mutation swamps selection and the fixed point is near-uniform — the philosophically interesting feed/starve regime (selection-dominated, where collapse actually threatens) is exactly what's not covered.

**Overreach 7 — the README and the headline thesis.** "One primitive, one axiom. Objects are theorems" describes no artifact in this repo — Series 3 is ZFC-in-Lean with no observation axiom. And the trade-off thesis ("the mathematics says you can't have both existence and the unbounded version") conflates "exists as a set" with "exists": the hyperuniverse exists perfectly well as a proper class under ZFC+AFA, and a class-based or algebraic-set-theory mechanization is a road not taken, not a road proved closed. The honest form is "not both within a set-sized, Mathlib-mechanized carrier." A ROSR-ist can accept proper-class reality without blinking.

**Smaller problems.** Criterion (iii) is discharged under a deflated reading — in a powerset coalgebra, edges have no identity; "relations" are just successor states, so binary relations are never themselves objects, which is what the philosophy actually asserts. `spec/ws8/00-holes.md` is a raw session transcript pasted into the spec tree (with chatty preamble intact), the ws1 spec numbering differs from the others, `ws7/02-design` lacks an extension, and `04-design-md` is a typo'd filename — cosmetic, but it undercuts the protocol's own rigor claims. And the blind-review layer is Claude reviewing Claude; for the publication portfolio, that's a limitation to disclose, not independence to claim.

The strongest genuine finding — the fracture pattern, global claims paying for existence — survives this audit in weakened form, and the strict-law impossibility plus the QPF construction are publishable content. But the summaries currently claim six-of-seven criteria at a strength the Lean doesn't deliver: (i) has no theorem, (iv)'s canonicity is definitional, (vi) rests on trivialities plus an unproved hypothesis, and the witnessed Goldilocks tuple doesn't exist yet. The `hcard` discharge and a concrete `κ₀` instantiation are cheap and would fix the worst of it; the atomless subcarrier and a real canonicity statement are the substantive next moves. Want me to draft the `hcard` proof and the `ℵ₀` instantiation as a concrete patch?
