/-
# `Cl(𝕋)` — the free traced symmetric monoidal category over a signature

This builds the **free traced SMC** on a signature, and the **universal (literal) functor**
out of it into any `TracedSMC` — the last named frontier of Layer 4.

A signature is a type of **colors** `C` and a family of **generating morphisms**
`G : Obj C → Obj C → Type`. From it:

* `Obj C` — objects, freely generated from colors by `⊗` and the unit (§ syntax);
* `Term` — morphism syntax, freely generated by `id, comp, ⊗, braid, trace`, the structural
  isos, and the generators;
* `Rel` — the congruence generated by **exactly the `TracedSMC` axioms** (category laws, the
  iso round-trips, and the seven JSV trace laws — *the same set the typeclass carries, and no
  more*: no pentagon/triangle/hexagon, which the typeclass also omits);
* `Cl 𝕋 := Quot Rel` — and the theorem that `Cl 𝕋` is itself a `TracedSMC` (`clTracedSMC`);
* `interp` / `Cl.functor` — the universal property: a model of the signature in `𝒟` extends
  to a traced functor `Cl 𝕋 → 𝒟`, with `Cl.functor_unique` (any two agreeing on generators
  agree everywhere).

This file is the **syntax and the interpretation** (Layer 1); the quotient `Cl` and the
universal functor follow.
-/
import RelExist.Traced

namespace RelExist.Free

open RelExist.Traced

universe u

/-! ### Objects — freely generated from colors by `⊗` and the unit -/

/-- Objects of the free category: the free `⊗`/unit structure on the colors `C`. -/
inductive Obj (C : Type u) where
  | gen : C → Obj C
  | unit : Obj C
  | tens : Obj C → Obj C → Obj C

/-! ### Morphism syntax — freely generated by the SMC + trace operations -/

variable {C : Type u}

/-- The morphism **syntax** of the free traced SMC over the signature `(C, G)`. Each
constructor is one piece of `TracedSMC` structure; `gen` injects the signature's generators. -/
inductive Term (G : Obj C → Obj C → Type u) : Obj C → Obj C → Type u where
  | id (X : Obj C) : Term G X X
  | comp {X Y Z : Obj C} : Term G X Y → Term G Y Z → Term G X Z
  | tensH {X Y Z W : Obj C} : Term G X Y → Term G Z W → Term G (.tens X Z) (.tens Y W)
  | braid (X Y : Obj C) : Term G (.tens X Y) (.tens Y X)
  | tr {X Y U : Obj C} : Term G (.tens X U) (.tens Y U) → Term G X Y
  | aHom (X Y Z : Obj C) : Term G (.tens (.tens X Y) Z) (.tens X (.tens Y Z))
  | aInv (X Y Z : Obj C) : Term G (.tens X (.tens Y Z)) (.tens (.tens X Y) Z)
  | ruHom (X : Obj C) : Term G (.tens X .unit) X
  | ruInv (X : Obj C) : Term G X (.tens X .unit)
  | luHom (X : Obj C) : Term G (.tens .unit X) X
  | luInv (X : Obj C) : Term G X (.tens .unit X)
  | gen {X Y : Obj C} : G X Y → Term G X Y

/-! ### Interpretation into a model — the universal map on syntax

Given a `TracedSMC` `𝒟`, a reading `ιC` of colors as objects, and a reading `ιG` of the
generators as morphisms, every object and every term is interpreted, structure-preservingly.
-/

variable {G : Obj C → Obj C → Type u} (𝒟 : TracedSMC.{u, u})

/-- Interpret an object: colors go to `ιC`, `⊗`/unit go to `𝒟`'s. -/
def interpObj (ιC : C → 𝒟.Obj) : Obj C → 𝒟.Obj
  | .gen c => ιC c
  | .unit => 𝒟.unit
  | .tens X Y => 𝒟.tens (interpObj ιC X) (interpObj ιC Y)

variable (ιC : C → 𝒟.Obj)
  (ιG : {X Y : Obj C} → G X Y → 𝒟.Hom (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y))

/-- Interpret a term as a morphism of `𝒟` — each syntactic constructor to its `𝒟` operation.
This is the **universal map on syntax**: it preserves `id, comp, ⊗, braid, trace`, the
structural isos, and sends generators to their chosen images. -/
def interpTerm : {X Y : Obj C} → Term G X Y → 𝒟.Hom (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y)
  | _, _, .id X => 𝒟.id (interpObj 𝒟 ιC X)
  | _, _, .comp f g => 𝒟.comp (interpTerm f) (interpTerm g)
  | _, _, .tensH f g => 𝒟.tensH (interpTerm f) (interpTerm g)
  | _, _, .braid X Y => 𝒟.braid (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y)
  | _, _, .tr f => 𝒟.trace (interpTerm f)
  | _, _, .aHom X Y Z =>
      𝒟.aHom (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y) (interpObj 𝒟 ιC Z)
  | _, _, .aInv X Y Z =>
      𝒟.aInv (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y) (interpObj 𝒟 ιC Z)
  | _, _, .ruHom X => 𝒟.ruHom (interpObj 𝒟 ιC X)
  | _, _, .ruInv X => 𝒟.ruInv (interpObj 𝒟 ιC X)
  | _, _, .luHom X => 𝒟.luHom (interpObj 𝒟 ιC X)
  | _, _, .luInv X => 𝒟.luInv (interpObj 𝒟 ιC X)
  | _, _, .gen g => ιG g

/-! ### The congruence — exactly the `TracedSMC` equations

`Rel` is the congruence on terms generated by the equations the `TracedSMC` typeclass
carries: the category laws, the structural-iso round-trips, and the seven JSV trace laws —
*and nothing more* (no pentagon/triangle/hexagon, which the typeclass also omits). Quotienting
by it gives the free model of the typeclass on the signature. -/

/-- The congruence generated by the `TracedSMC` axioms on the free syntax. -/
inductive Rel {G : Obj C → Obj C → Type u} : {X Y : Obj C} → Term G X Y → Term G X Y → Prop
  -- equivalence
  | refl {X Y} (f : Term G X Y) : Rel f f
  | symm {X Y} {f g : Term G X Y} : Rel f g → Rel g f
  | trans {X Y} {f g h : Term G X Y} : Rel f g → Rel g h → Rel f h
  -- congruence
  | comp_cong {X Y Z} {f f' : Term G X Y} {g g' : Term G Y Z} :
      Rel f f' → Rel g g' → Rel (.comp f g) (.comp f' g')
  | tensH_cong {X Y Z W} {f f' : Term G X Y} {g g' : Term G Z W} :
      Rel f f' → Rel g g' → Rel (.tensH f g) (.tensH f' g')
  | tr_cong {X Y U} {f f' : Term G (.tens X U) (.tens Y U)} :
      Rel f f' → Rel (.tr f) (.tr f')
  -- category laws
  | id_comp {X Y} (f : Term G X Y) : Rel (.comp (.id X) f) f
  | comp_id {X Y} (f : Term G X Y) : Rel (.comp f (.id Y)) f
  | assoc {W X Y Z} (f : Term G W X) (g : Term G X Y) (h : Term G Y Z) :
      Rel (.comp (.comp f g) h) (.comp f (.comp g h))
  -- structural iso round-trips
  | a_hom_inv (X Y Z) : Rel (.comp (.aHom X Y Z) (.aInv X Y Z)) (.id _)
  | a_inv_hom (X Y Z) : Rel (.comp (.aInv X Y Z) (.aHom X Y Z)) (.id _)
  | ru_hom_inv (X) : Rel (.comp (.ruHom X) (.ruInv X)) (.id _)
  | ru_inv_hom (X) : Rel (.comp (.ruInv X) (.ruHom X)) (.id _)
  | lu_hom_inv (X) : Rel (.comp (.luHom X) (.luInv X)) (.id _)
  | lu_inv_hom (X) : Rel (.comp (.luInv X) (.luHom X)) (.id _)
  -- JSV trace laws
  | trace_nat_left {X X' Y U} (g : Term G X' X) (f : Term G (.tens X U) (.tens Y U)) :
      Rel (.tr (.comp (.tensH g (.id U)) f)) (.comp g (.tr f))
  | trace_nat_right {X Y Y' U} (f : Term G (.tens X U) (.tens Y U)) (g : Term G Y Y') :
      Rel (.tr (.comp f (.tensH g (.id U)))) (.comp (.tr f) g)
  | trace_slide {X Y U V} (f : Term G (.tens X U) (.tens Y V)) (h : Term G V U) :
      Rel (.tr (.comp f (.tensH (.id Y) h))) (.tr (.comp (.tensH (.id X) h) f))
  | trace_yank (U) : Rel (.tr (.braid U U)) (.id U)
  | trace_vanish_unit {X Y} (f : Term G (.tens X .unit) (.tens Y .unit)) :
      Rel (.tr f) (.comp (.ruInv X) (.comp f (.ruHom Y)))
  | trace_vanish_tens {X Y U V} (f : Term G (.tens X (.tens U V)) (.tens Y (.tens U V))) :
      Rel (.tr f) (.tr (.tr (.comp (.aHom X U V) (.comp f (.aInv Y U V)))))
  | trace_superpose {W X Y U} (f : Term G (.tens X U) (.tens Y U)) :
      Rel (.tr (.comp (.aHom W X U) (.comp (.tensH (.id W) f) (.aInv W Y U))))
          (.tensH (.id W) (.tr f))

/-! ### `Cl 𝕋 := Quot Rel` and its operations -/

variable (G : Obj C → Obj C → Type u)

/-- Morphisms of the free traced SMC: terms modulo the congruence. -/
abbrev Hom (X Y : Obj C) : Type u := Quot (@Rel C G X Y)

/-- The identity morphism. -/
def qid (X : Obj C) : Hom G X X := Quot.mk _ (Term.id X)

/-- Composition, descended to the quotient. -/
def qcomp {X Y Z} : Hom G X Y → Hom G Y Z → Hom G X Z :=
  Quot.lift
    (fun f => Quot.lift (fun g => Quot.mk (@Rel C G X Z) (Term.comp f g))
        (fun _ _ hg => Quot.sound (Rel.comp_cong (Rel.refl _) hg)))
    (fun _ _ hf => funext fun qg =>
      Quot.inductionOn qg (fun _ => Quot.sound (Rel.comp_cong hf (Rel.refl _))))

/-- Tensor of morphisms, descended to the quotient. -/
def qtensH {X Y Z W} : Hom G X Y → Hom G Z W → Hom G (.tens X Z) (.tens Y W) :=
  Quot.lift
    (fun f => Quot.lift (fun g => Quot.mk (@Rel C G _ _) (Term.tensH f g))
        (fun _ _ hg => Quot.sound (Rel.tensH_cong (Rel.refl _) hg)))
    (fun _ _ hf => funext fun qg =>
      Quot.inductionOn qg (fun _ => Quot.sound (Rel.tensH_cong hf (Rel.refl _))))

/-- Trace, descended to the quotient. -/
def qtr {X Y U} : Hom G (.tens X U) (.tens Y U) → Hom G X Y :=
  Quot.lift (fun f => Quot.mk (@Rel C G X Y) (Term.tr f))
    (fun _ _ hf => Quot.sound (Rel.tr_cong hf))

/-- **`Cl 𝕋` is a traced symmetric monoidal category.** Every operation descends to the
quotient, and every `TracedSMC` axiom holds because the corresponding `Rel` generator makes
the two sides equal. This is the *free* such category on the signature. -/
def clTracedSMC : TracedSMC.{u, u} where
  Obj := Obj C
  Hom := Hom G
  id := qid G
  comp := qcomp G
  id_comp := by intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (Rel.id_comp f)
  comp_id := by intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (Rel.comp_id f)
  assoc := by
    intro W X Y Z f g h
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    induction h using Quot.ind with | _ h =>
    exact Quot.sound (Rel.assoc f g h)
  tens := Obj.tens
  unit := Obj.unit
  tensH := qtensH G
  braid := fun X Y => Quot.mk _ (Term.braid X Y)
  trace := qtr G
  aHom := fun X Y Z => Quot.mk _ (Term.aHom X Y Z)
  aInv := fun X Y Z => Quot.mk _ (Term.aInv X Y Z)
  a_hom_inv := fun X Y Z => Quot.sound (Rel.a_hom_inv X Y Z)
  a_inv_hom := fun X Y Z => Quot.sound (Rel.a_inv_hom X Y Z)
  ruHom := fun X => Quot.mk _ (Term.ruHom X)
  ruInv := fun X => Quot.mk _ (Term.ruInv X)
  ru_hom_inv := fun X => Quot.sound (Rel.ru_hom_inv X)
  ru_inv_hom := fun X => Quot.sound (Rel.ru_inv_hom X)
  luHom := fun X => Quot.mk _ (Term.luHom X)
  luInv := fun X => Quot.mk _ (Term.luInv X)
  lu_hom_inv := fun X => Quot.sound (Rel.lu_hom_inv X)
  lu_inv_hom := fun X => Quot.sound (Rel.lu_inv_hom X)
  trace_nat_left := by
    intro X X' Y U g f
    induction g using Quot.ind with | _ g =>
    induction f using Quot.ind with | _ f =>
    exact Quot.sound (Rel.trace_nat_left g f)
  trace_nat_right := by
    intro X Y Y' U f g
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    exact Quot.sound (Rel.trace_nat_right f g)
  trace_slide := by
    intro X Y U V f h
    induction f using Quot.ind with | _ f =>
    induction h using Quot.ind with | _ h =>
    exact Quot.sound (Rel.trace_slide f h)
  trace_yank := fun U => Quot.sound (Rel.trace_yank U)
  trace_vanish_unit := by
    intro X Y f; induction f using Quot.ind with | _ f => exact Quot.sound (Rel.trace_vanish_unit f)
  trace_vanish_tens := by
    intro X Y U V f; induction f using Quot.ind with | _ f => exact Quot.sound (Rel.trace_vanish_tens f)
  trace_superpose := by
    intro W X Y U f; induction f using Quot.ind with | _ f => exact Quot.sound (Rel.trace_superpose f)

/-! ### The universal (literal) functor `Cl 𝕋 ⟶ 𝒟` -/

variable (𝒟 : TracedSMC.{u, u}) (ιC : C → 𝒟.Obj)
  (ιG : {X Y : Obj C} → G X Y → 𝒟.Hom (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y))

/-- The interpretation **respects the congruence**: each `Rel` generator is sent to a true
equation of `𝒟` (its corresponding `TracedSMC` axiom), and the equivalence/congruence
generators to `Eq`'s own laws. Hence the interpretation descends to the quotient. -/
theorem interp_respects {X Y} {a b : Term G X Y} (h : Rel a b) :
    interpTerm 𝒟 ιC ιG a = interpTerm 𝒟 ιC ιG b := by
  induction h with
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | comp_cong _ _ ihf ihg =>
      show 𝒟.comp _ _ = 𝒟.comp _ _; rw [ihf, ihg]
  | tensH_cong _ _ ihf ihg =>
      show 𝒟.tensH _ _ = 𝒟.tensH _ _; rw [ihf, ihg]
  | tr_cong _ ih =>
      show 𝒟.trace _ = 𝒟.trace _; rw [ih]
  | id_comp f => exact 𝒟.id_comp _
  | comp_id f => exact 𝒟.comp_id _
  | assoc f g h => exact 𝒟.assoc _ _ _
  | a_hom_inv X Y Z => exact 𝒟.a_hom_inv _ _ _
  | a_inv_hom X Y Z => exact 𝒟.a_inv_hom _ _ _
  | ru_hom_inv X => exact 𝒟.ru_hom_inv _
  | ru_inv_hom X => exact 𝒟.ru_inv_hom _
  | lu_hom_inv X => exact 𝒟.lu_hom_inv _
  | lu_inv_hom X => exact 𝒟.lu_inv_hom _
  | trace_nat_left g f => exact 𝒟.trace_nat_left _ _
  | trace_nat_right f g => exact 𝒟.trace_nat_right _ _
  | trace_slide f h => exact 𝒟.trace_slide _ _
  | trace_yank U => exact 𝒟.trace_yank _
  | trace_vanish_unit f => exact 𝒟.trace_vanish_unit _
  | trace_vanish_tens f => exact 𝒟.trace_vanish_tens _
  | trace_superpose f => exact 𝒟.trace_superpose _

/-- **The literal universal functor `Cl 𝕋 ⟶ 𝒟`.** A model of the signature in `𝒟` (a reading
`ιC` of colors, `ιG` of generators) extends to a genuine traced functor out of the free
traced SMC. Objects and all structure are preserved definitionally; the morphism map is the
interpretation, descended through the quotient by `interp_respects`. -/
def functor : TracedFunctor (clTracedSMC G) 𝒟 where
  obj := interpObj 𝒟 ιC
  map := fun {_ _} => Quot.lift (interpTerm 𝒟 ιC ιG) (fun _ _ h => interp_respects G 𝒟 ιC ιG h)
  obj_tens := fun _ _ => rfl
  obj_unit := rfl
  map_id := fun _ => rfl
  map_comp := by
    intro X Y Z f g
    induction f using Quot.ind with | _ f =>
    induction g using Quot.ind with | _ g =>
    rfl

/-- **Uniqueness — the universal property.** Any morphism map `m` out of `Cl 𝕋` that
preserves *all* the structure (identities, composition, tensor, braiding, trace, and the
structural isos) and agrees with `ιG` on the generators **equals** the universal functor's
map. So the model `(ιC, ιG)` determines the traced functor uniquely: `Cl 𝕋` is genuinely free.
(`TracedFunctor` itself only requires preserving `id`/`comp`, so braid/trace/iso preservation
must be hypothesised explicitly — exactly the data of a model of the signature.) -/
theorem functor_unique
    (m : {X Y : Obj C} → Hom G X Y → 𝒟.Hom (interpObj 𝒟 ιC X) (interpObj 𝒟 ιC Y))
    (h_id : ∀ X, m (qid G X) = 𝒟.id _)
    (h_comp : ∀ {X Y Z} (f : Hom G X Y) (g : Hom G Y Z),
      m (qcomp G f g) = 𝒟.comp (m f) (m g))
    (h_tensH : ∀ {X Y Z W} (f : Hom G X Y) (g : Hom G Z W),
      m (qtensH G f g) = 𝒟.tensH (m f) (m g))
    (h_braid : ∀ X Y, m (Quot.mk _ (Term.braid X Y)) = 𝒟.braid _ _)
    (h_tr : ∀ {X Y U} (f : Hom G (.tens X U) (.tens Y U)), m (qtr G f) = 𝒟.trace (m f))
    (h_aHom : ∀ X Y Z, m (Quot.mk _ (Term.aHom X Y Z)) = 𝒟.aHom _ _ _)
    (h_aInv : ∀ X Y Z, m (Quot.mk _ (Term.aInv X Y Z)) = 𝒟.aInv _ _ _)
    (h_ruHom : ∀ X, m (Quot.mk _ (Term.ruHom X)) = 𝒟.ruHom _)
    (h_ruInv : ∀ X, m (Quot.mk _ (Term.ruInv X)) = 𝒟.ruInv _)
    (h_luHom : ∀ X, m (Quot.mk _ (Term.luHom X)) = 𝒟.luHom _)
    (h_luInv : ∀ X, m (Quot.mk _ (Term.luInv X)) = 𝒟.luInv _)
    (h_gen : ∀ {X Y} (g : G X Y), m (Quot.mk _ (Term.gen g)) = ιG g)
    {X Y} (f : Hom G X Y) :
    m f = (functor G 𝒟 ιC ιG).map f := by
  induction f using Quot.ind with | _ t =>
  induction t with
  | id X => exact h_id X
  | comp f g ihf ihg =>
      have hc := h_comp (Quot.mk _ f) (Quot.mk _ g); rw [ihf, ihg] at hc; exact hc
  | tensH f g ihf ihg =>
      have ht := h_tensH (Quot.mk _ f) (Quot.mk _ g); rw [ihf, ihg] at ht; exact ht
  | braid X Y => exact h_braid X Y
  | tr f ih =>
      have htr := h_tr (Quot.mk _ f); rw [ih] at htr; exact htr
  | aHom X Y Z => exact h_aHom X Y Z
  | aInv X Y Z => exact h_aInv X Y Z
  | ruHom X => exact h_ruHom X
  | ruInv X => exact h_ruInv X
  | luHom X => exact h_luHom X
  | luInv X => exact h_luInv X
  | gen g => exact h_gen g

end RelExist.Free
